name: PR CI

on:
  pull_request:
  push:
    paths:
      - ".aspell.en.pws"
      - "CV.tex"
      - "cv.sty"
      - ".github/workflows/publish.yml"
      - ".github/workflows/pr.yml"
    branches:
      - "*"
      - "!master"

jobs:
  pr-ci:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Install dependences
        run: |
          make deps

      - name: Set environment vars
        run: |
          echo "DATE=$(date --iso-8601=date)" >> $GITHUB_ENV

      - name: Build CV
        run: make create-pdf
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          DATE: ${{ env.DATE }}
