name: PR CI

on:
  pull_request:
    paths:
      - ".aspell.en.pws"
      - "leadership-cv.tex"
      - "advisory-cv.tex"
      - "cv.sty"
      - "Makefile"
      - ".github/workflows/publish.yml"
      - ".github/workflows/pr.yml"
  push:
    paths:
      - ".aspell.en.pws"
      - "leadership-cv.tex"
      - "advisory-cv.tex"
      - "cv.sty"
      - "Makefile"
      - ".github/workflows/publish.yml"
      - ".github/workflows/pr.yml"
    branches:
      - "*"
      - "!master"

jobs:
  detect-cvs:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      pull-requests: read
    outputs:
      cvs: ${{ steps.filter.outputs.changes }}

    steps:
      - name: Checkout code
        uses: actions/checkout@v5
        with:
          fetch-depth: 0

      - name: Detect changed CVs
        id: filter
        uses: dorny/paths-filter@v4
        with:
          base: ${{ github.ref }}
          filters: |
            leadership-cv:
              - 'leadership-cv.tex'
              - '.aspell.en.pws'
              - 'cv.sty'
              - 'Makefile'
              - '.github/workflows/publish.yml'
              - '.github/workflows/pr.yml'
            advisory-cv:
              - 'advisory-cv.tex'
              - '.aspell.en.pws'
              - 'cv.sty'
              - 'Makefile'
              - '.github/workflows/publish.yml'
              - '.github/workflows/pr.yml'

  build-check:
    needs: detect-cvs
    if: needs.detect-cvs.outputs.cvs != '[]'
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        cv: ${{ fromJSON(needs.detect-cvs.outputs.cvs) }}

    steps:
      - name: Checkout code
        uses: actions/checkout@v6

      - name: Install dependences
        run: |
          make deps

      - name: Spellcheck ${{ matrix.cv }}
        run: |
          make spellcheck CVS=${{ matrix.cv }}

      - name: Build ${{ matrix.cv }}
        run: |
          make create-pdf CVS=${{ matrix.cv }}

      - name: Check ${{ matrix.cv }} length
        run: |
          make check-length CVS=${{ matrix.cv }}
