name: PR CI

on:
  pull_request:
    branches:
      - "*"
      - "!master"
  push:
    paths:
      - "CV.tex"
      - ".github/workflows/publish.yml"
      - ".github/workflows/pr.yml"

jobs:
  pr-ci:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Install dependences
        run: |
          make deps

      - name: Set environment vars
        run: |
          echo "DATE=$(date --iso-8601=date)" >> $GITHUB_ENV

      - name: Build CV
        run: make create-pdf
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          DATE: ${{ env.DATE }}
