name: Publish CV

on:
  push:
    paths:
      - ".aspell.en.pws"
      - "leadership-cv.tex"
      - "advisory-cv.tex"
      - "cv.sty"
      - "Makefile"
      - ".github/workflows/publish.yml"
      - ".github/workflows/pr.yml"
    branches:
      - master

jobs:
  detect-cvs:
    runs-on: ubuntu-latest
    permissions:
      contents: read
    outputs:
      cvs: ${{ steps.filter.outputs.changes }}

    steps:
      - name: Checkout code
        uses: actions/checkout@v5
        with:
          fetch-depth: 0

      - name: Detect changed CVs
        id: filter
        uses: dorny/paths-filter@v4
        with:
          base: ${{ github.ref }}
          filters: |
            leadership-cv:
              - 'leadership-cv.tex'
              - '.aspell.en.pws'
              - 'cv.sty'
              - 'Makefile'
              - '.github/workflows/publish.yml'
              - '.github/workflows/pr.yml'
            advisory-cv:
              - 'advisory-cv.tex'
              - '.aspell.en.pws'
              - 'cv.sty'
              - 'Makefile'
              - '.github/workflows/publish.yml'
              - '.github/workflows/pr.yml'

  build-check:
    needs: detect-cvs
    if: needs.detect-cvs.outputs.cvs != '[]'
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        cv: ${{ fromJSON(needs.detect-cvs.outputs.cvs) }}

    steps:
      - name: Checkout code
        uses: actions/checkout@v5

      - name: Install dependences
        run: |
          make deps

      - name: Spellcheck ${{ matrix.cv }}
        run: |
          make spellcheck CVS=${{ matrix.cv }}

      - name: Build ${{ matrix.cv }}
        run: |
          make create-pdf CVS=${{ matrix.cv }}

      - name: Check ${{ matrix.cv }} length
        run: |
          make check-length CVS=${{ matrix.cv }}

      - name: Set environment vars
        run: |
          echo "DATE=$(date --iso-8601=date)" >> "$GITHUB_ENV"

      - name: Rename ${{ matrix.cv }} PDF
        run: |
          make rename CVS=${{ matrix.cv }}
        env:
          DATE: ${{ env.DATE }}

      - name: Upload ${{ matrix.cv }} PDF
        uses: actions/upload-artifact@v4
        with:
          name: ${{ matrix.cv }}-pdf
          path: Oscar.Barlow.*.pdf
          if-no-files-found: error

  publish:
    needs:
      - detect-cvs
      - build-check
    if: needs.detect-cvs.outputs.cvs != '[]'
    runs-on: ubuntu-latest
    permissions:
      contents: write

    steps:
      - name: Download PDFs
        uses: actions/download-artifact@v4
        with:
          pattern: "*-pdf"
          merge-multiple: true

      - name: Set environment vars
        run: |
          echo "DATE=$(date --iso-8601=date)" >> "$GITHUB_ENV"

      - name: Publish changed CVs
        run: |
          gh release create "$DATE" -t "Oscar Barlow CVs $DATE" -n "Oscar Barlow's changed CVs for $DATE. PDFs are available to download from the links below." ./*.pdf
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          DATE: ${{ env.DATE }}
