name: Publish CV

on:
  push:
    paths:
      - ".aspell.en.pws"
      - "CV.tex"
      - "cv.sty"      
      - ".github/workflows/publish.yml"
    branches:
      - master

jobs:
  publish:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Install dependences
        run: |
          make deps

      - name: Spellcheck
        run: |
          if make -s spellcheck; then
            echo "No spelling mistakes found."
            exit 0
          else
            echo "Spelling mistakes found."
            exit 1
          fi

      - name: Set environment vars
        run: |
          echo "DATE=$(date --iso-8601=date)" >> $GITHUB_ENV

      - name: Release
        run: |
          make ci
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          DATE: ${{ env.DATE }}

      - name: Check length
        run: |
          if make -s check-length < 3; then
            "CV is 2 pages or less"
            exit 0
          else
            echo "CV is too long."
            exit 1
              fi
